# =============================================
# Formelsammlung Physik in reinem Bash
# =============================================

# HILFSFUNKTION: Warte explizit auf 'c' (Master-Clean-Code)
wait_for_c() {
    echo ""
    echo ""
    echo ""
    echo -e "Eingabe ${RED}[c]${NOCOLOR} zum Beenden/Zurückgehen"
    echo -e "Eingabe ${RED}[a]${NOCOLOR} zum Ausklappen aller Kapitel"
    echo -n ""
    while true; do
        read -n1 -s key # -n1 = 1 Zeichen, -s = kein Echo
        key=${key,,} # Automatisch Kleinbuchstabe
        if [ "$key" = "c" ]; then
            echo # Saubere neue Zeile
            return # Zurück ins Haupt-while
        fi
        # Andere Tasten → nichts tun (stilles Warten)
    done
}

NOCOLOR='\033[0m'
BLUE='\033[0;34m'
RED='\033[0;31m'
ORANGE='\033[38;5;208m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
BOLD='\033[1m'
GRAY='\033[90m'

while true; do
    clear
    echo -e "${BLUE}>${NOCOLOR} Formelsammlung Physik"
    echo ""
    echo -e "${BLUE}>>${NOCOLOR} Naturkonstanten ${GRAY}[0]${NOCOLOR}"
    echo ""
    echo -e "${BLUE}>>${NOCOLOR} Newton'sche Mechanik ${GRAY}[1]${NOCOLOR}"
    echo -e "${BLUE}>>${NOCOLOR} Analytische Mechanik ${GRAY}[2]${NOCOLOR}"
    echo -e "${BLUE}>>${NOCOLOR} Elektromagnetismus ${GRAY}[3]${NOCOLOR}"
    echo -e "${BLUE}>>${NOCOLOR} Optik ${GRAY}[4]${NOCOLOR}"
    echo -e "${BLUE}>>${NOCOLOR} Quantenmechanik ${GRAY}[5]${NOCOLOR}"
    echo -e "${BLUE}>>${NOCOLOR} Festkörperphysik ${GRAY}[6]${NOCOLOR}"
    echo -e "${BLUE}>>${NOCOLOR} Relativitätstheorie ${GRAY}[7]${NOCOLOR}"
    echo ""
    echo ""
    echo ""
    echo ""
    echo -e "Eingabe ${RED}[0]${NOCOLOR}-${RED}[7]${NOCOLOR}, um das jeweilige Kapitel zu öffnen"
    echo -e "Eingabe ${RED}[c]${NOCOLOR} zum Beenden/Zurückgehen"
    echo -e "Eingabe ${RED}[↑]${NOCOLOR},${RED}[↓]${NOCOLOR} zum navigieren des Cursors"
    echo -e "Eingabe ${RED}[i]${NOCOLOR} für mehr Informationen zum markierten Thema"
    echo -n ""
    read -n1 -s wahl
    echo
    wahl=${wahl,,} # Kleinbuchstaben-Normierung
    
    
    
    
    if [ "$wahl" = "0" ]; then
        clear
        echo -e "${BLUE}>${NOCOLOR} Formelsammlung Physik"
        echo -e "${BLUE}>>${NOCOLOR} Naturkonstanten"
        echo ""
        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Mechanik${NOCOLOR}"
        echo " Gravitationskonstante:		G = 6.67430(15)×10⁻¹¹ m³ kg⁻¹ s⁻²"
        echo " Erdmasse:			M_⊕ = 5.97237(±0.00029)×10²⁴ kg"
        echo " Sonnenmasse:			M_☉ = 1.9885(±0.0003)×10³⁰ kg"
        echo ""
        echo ""
        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Elektromagnetismus${NOCOLOR}"
        echo " Elementarladung:		e = 1.602176634×10⁻¹⁹ C (exakt)"
        echo " Lichtgeschwindigkeit:		c = 299792458 m/s (exakt)"
        echo " Elektrische Feldkonstante:	ε₀ = 8.8541878128(13)×10⁻¹² F/m"
        echo " Magnetische Feldkonstante:	μ₀ = 1.25663706212(19)×10⁻⁶ H/m"
        echo " Coulomb-Konstante:		k = 8.987551789×10⁹ N·m²/C²"
        echo ""
        echo ""
        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Quantenmechanik${NOCOLOR}"
        echo " Plancksche Konstante:		h = 6.62607015×10⁻³⁴ J·s (exakt)"
        echo " Reduzierte Plancksche Konst.:	ħ = 1.054571817…×10⁻³⁴ J·s"
        echo " Feinstrukturkonstante:		α ≈ 7.2973525693(11)×10⁻³"
        echo " Rydberg-Konstante:		R_∞ = 1.0973731568160(21)×10⁷ m⁻¹"
        echo " Bohr-Radius:			a₀ = 5.29177210903(80)×10⁻¹¹ m"
        echo ""
        echo ""
        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Thermodynamik${NOCOLOR}"
        echo " Avogadro-Konstante:		N_A = 6.02214076×10²³ mol⁻¹ (exakt)"
        echo " Boltzmann-Konstante:		k_B = 1.380649×10⁻²³ J/K (exakt)"
        echo " Gaskonstante:			R = 8.314462618 J mol⁻¹ K⁻¹"
        wait_for_c
        
        
        
    elif [ "$wahl" = "1" ]; then
        clear
        echo -e "${BLUE}>${NOCOLOR} Formelsammlung Physik"
        echo -e "${BLUE}>>${NOCOLOR} Newton'sche Mechanik"
        echo ""
        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Axiome und grundlegende Definitionen${NOCOLOR}"
        echo " 2. Axiom ''Bewegungsgleichung'':	F = m a"
        echo " 3. Axiom ''Actio = Reactio'': 		F_{12} = -F_{21}"
        echo " Geschwindigkeit: 			v := lim_{h->0} (x(t+h)-x(h)) / h"
        echo " Bescheunigung: 			a := lim_{h->0} (v(t+h)-v(h)) / h"
        echo ""
        echo ""
        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Erhaltungssätze${NOCOLOR}"
        echo " Kinetische Energie: 	T = 1/2 m v²"
        echo " Potential: 		F = -grad V"
        echo " Energie: 		E = T + V"
        echo " Impuls: 		p = m V"
        echo " Drehimpuls:		L = r × p"
        echo " Drehmoment:		M = r × F"
        echo ""
        echo ""
        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Modellsysteme der Mechanik des Massenpunkts${NOCOLOR}"
        echo -e "${BLUE}>>>>${NOCOLOR} Harmonischer Oszillator"
        echo " Potential:		V = 1/2 k x²"
        echo " Ort:			x(t) = v0/omega sin(omega t) + x0 cos(omega t) ="
        echo "			     = A sin(omega t + delta)"
        echo " Energie:		E = 1/2 k/m x² A²"
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Harmonischer Oszillator mit Stokes-Reibung"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Getriebener harmonischer Oszillator"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Schiefer Wurf"
        echo " Höhe-Weite Zusammenhang:	y(x) = -g/(2v0²cos²alpha) x² + tan alpha x"
        echo " Maximale Höhe des Wurfs:	H = v0²/(2g) sin²alpha"
        echo " Wurfweite:			L = 2v0² sin(alpha) cos(alpha)/g"
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Fadenpendel"
        echo " Periodendauer:		T = 2pi sqrt(l/g)"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Reale Körper${NOCOLOR}"
        echo -e "${BLUE}>>>>${NOCOLOR} Reibung"
        echo " Haftreibung:		F_H = mu_H F_N"
        echo " Gleitreibung:		F_G = mu_G F_N"
        echo " Rollreibung:		M_R = mu_R F_N"
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Deformation"
        echo "..."
        wait_for_c
        
        
        
    elif [ "$wahl" = "2" ]; then
        clear
        echo -e "${BLUE}>${NOCOLOR} Formelsammlung Physik"
        echo -e "${BLUE}>>${NOCOLOR} Analytische Mechanik"
        echo ""
        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Formalismen der Analytischen Mechanik${NOCOLOR}"
        echo "Lagrange-Gleichungen 1. Art:	..."
        echo "Lagrange-Gleichung 2. Art:	d/dt (∂L/∂q̇_k) - ∂L/∂q_k = 0"
        echo "Hamilton-Gleichungen:		q̇ = ∂H/∂p, ṗ = -∂H/∂q"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Prinzip der kleinsten Wirkung${NOCOLOR}"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Noether-Theorem${NOCOLOR}"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Zweikörperproblem${NOCOLOR}"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Starre Körper${NOCOLOR}"
        echo "..."
        wait_for_c
    elif [ "$wahl" = "3" ]; then
        clear
        echo -e "${BLUE}>${NOCOLOR} Formelsammlung Physik"
        echo -e "${BLUE}>>${NOCOLOR} Elektromagnetismus"
        echo ""
        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Elektrostatik${NOCOLOR}"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Grenzflächenbedingung"
        echo "Normalkomponente E-Feld:	E_perp,A - E_perp,B = sigma/epsilon0"
        echo "Tangentialkomponente E-Feld:	E_||,A = E_||,B"
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Modellsysteme"
        echo -e "${BLUE}>>>>>${NOCOLOR} Punktladung"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>>>${NOCOLOR} Plattenkondensator"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>>>${NOCOLOR} Zylinderkondensator"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>>>${NOCOLOR} Elektrischer Dipol"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Magnetostatik${NOCOLOR}"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Modellsysteme"
        echo -e "${BLUE}>>>>>${NOCOLOR} Stromdurchflossener Draht"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>>>${NOCOLOR} Kreisstrom"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>>>${NOCOLOR} Zylinderspule"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>>>${NOCOLOR} Magnetischer Dipol"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>>>${NOCOLOR} Helmholtz-Spule"
        echo "..."
        echo ""
        echo ""

	echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Elektro- und Magnetostatik in Materie${NOCOLOR}"
        echo -e "${BLUE}>>>>${NOCOLOR} Dielektrika"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Magnetika"
        echo "..."
        echo ""
        echo ""

        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Elektrodynamik${NOCOLOR}"
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Elektromagnetische Welle"
        echo "..."
        echo ""
        echo ""

        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Elektronik${NOCOLOR}"
        echo "..."
        echo ""
        echo ""
        wait_for_c





    elif [ "$wahl" = "4" ]; then
        clear
        echo -e "${BLUE}>${NOCOLOR} Formelsammlung Physik"
        echo -e "${BLUE}>>${NOCOLOR} Optik"
        echo ""
        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Elektromagnetische Welle${NOCOLOR}"
        echo -e "${BLUE}>>>>${NOCOLOR} Ebene Welle"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Wellenpaket"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Reflexion und Transmission"
        echo " Snelliusches Brechungsgesetz: 		n₁ sinθ₁ = n₂ sinθ₂"
        echo " Reflexionsgesetz: 			θ_e = θ_r"
        echo " Fresnel'sche Formeln:			..."
        echo " Brewster Winkel:			..."
        echo " Totalreflexion:			..."
        echo ""
        echo ""

        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Geometrische Optik${NOCOLOR}"
        echo " Snelliusches Brechungsgesetz: n₁ sin θ₁ = n₂ sin θ₂"
        echo " Reflexionsgesetz: θ_i = θ_r"
	echo -e "${BLUE}>>>>${NOCOLOR} Modellsysteme"
	echo "..."
	echo ""
	echo ""
	echo -e "${BLUE}>>>>>${NOCOLOR} Kugelspiegel"
	echo "..."
	echo ""
	echo ""
	echo -e "${BLUE}>>>>>${NOCOLOR} Brechende Kugeloberfläche"
	echo "..."
	echo ""
	echo ""
	echo -e "${BLUE}>>>>>${NOCOLOR} Dünne Linse"
	echo "..."
	echo ""
	echo ""
	echo -e "${BLUE}>>>>${NOCOLOR} Matrizenverfahren"
	echo "..."
	echo ""
	echo ""
        wait_for_c


    elif [ "$wahl" = "5" ]; then
        clear
        echo -e "${BLUE}>${NOCOLOR} Formelsammlung Physik"
        echo -e "${BLUE}>>${NOCOLOR} Quantenmechanik"
        echo ""
        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Grundlegende Gleichungen${NOCOLOR}"
        echo " Zeitabhängige Schrödinger-Gl.:		iħ ∂ψ/∂t = Ĥψ"
        echo " Zeitunabhängige Schrödinger-Gl.:	Ĥψ = E ψ"
        echo " Eigenzustand:				ψ(x,t) = u(x) exp(-i/ħ E t)"
        echo ""
        echo " Wahrscheinlichkeitsdichte:		rho(x) = |ψ(x)|²"
        echo " Erwartungswert:			<Ô> = ∫ ψ* Ô ψ dV"
        echo " Varianz:				Var[Ô] = <Ô²> - <Ô>²"
        echo " Standardabweichung:			sigma[Ô] = sqrt(Var[Ô])"
        echo ""
        echo " Wahrscheinlichkeitsstromdichte:	j = ħ/2mi(ψ* grad ψ - ψ grad ψ*)"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}1d Modellsysteme${NOCOLOR}"
        echo -e "${BLUE}>>>>${NOCOLOR} Unendlich hoher Potentialtopf"
        echo " Potential:		..."
        echo " Energien:		En = pi² ħ² / (2mL²) n²"
        echo " Eigenzustände:		u_n(x) = sqrt(2/a) sin(pi n/a x)"
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Potentialstufe"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Potentialbarriere/Tunneleffekt"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Endlich hoher Potentialtopf"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Harmonischer Oszillator"
        echo " Potential:		V = 1/2 k x²"
        echo " Energien:		E_n = ħ omega (n+1/2)"
        echo " Eigenzustände:		1/(sqrt(n! 2^n) pi^1/4) H_n(x) exp(-x²/2)"
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Deltapotential"
        echo " Potential:		V = -V0 delta(x)"
        echo " Energie:		-m V0² / 2ħ²"
        echo " Zustand:		..."
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Teilchen auf einem Ring"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Wellenpaket"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}3d Modellsysteme${NOCOLOR}"
        echo -e "${BLUE}>>>>${NOCOLOR} Wasserstoffatom"
        echo " Potential:		V(r) = -Z e² / (4pi epsilon0) 1/r"
        echo " Energien:		E_n = -1/2 m c² alpha² Z²/n²"
        echo " Eigenzustände:		u_nlm(r,theta,phi) = R_nl(r) Y_lm(theta,phi)"
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} 3d harmonischer Oszillator"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>${NOCOLOR} ${ORANGE}Elektromagnetisches Feld und Spin${NOCOLOR}"
        echo " Pauli-Gleichung:	iħ ∂ψ/∂t = [(p - qA)²/(2m) + qφ - μ·B]ψ"
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Normaler Zeeman-Effekt"
        echo "..."
        echo ""
        echo ""
        echo -e "${BLUE}>>>>${NOCOLOR} Magnetresonanz"
        echo "..."
        echo ""
        echo ""
        wait_for_c
    elif [ "$wahl" = "6" ]; then
        clear
        echo -e "${BLUE}>${NOCOLOR} Formelsammlung Physik"
        echo -e "${BLUE}>>${NOCOLOR} Festkörperphysik"
        echo "..."
        echo ""
        echo ""
        wait_for_c
    elif [ "$wahl" = "7" ]; then
        clear
        echo -e "${BLUE}>${NOCOLOR} Formelsammlung Physik"
        echo -e "${BLUE}>>${NOCOLOR} Relativitätstheorie"
        echo "..."
        echo ""
        echo ""
        wait_for_c
    elif [ "$wahl" = "c" ]; then
        clear
        echo "Programm wird beendet."
        exit 0
    fi
done
